/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Yahtzee;
import java.net.URI;
import java.net.URISyntaxException;
import java.awt.Desktop;
import java.io.IOException;
import java.util.Arrays;

/**
 *
 * @author evrob0095
 */
public class Yahtzee extends javax.swing.JFrame {

    /**
     * Creates new form Yahtzee
     */
    public Yahtzee() {
        initComponents();
        //Setup start page
        GamePage.setVisible(false);
        scorePage.setVisible(false);
        player1.setEnabled(false);
        player2.setEnabled(false);
        player3.setEnabled(false);
        player4.setEnabled(false);
        
    }
    //Name variables
    String name1;
    String name2;
    String name3;
    String name4;
    
    //Scores for players
    int score1 = 0;
    int score2 = 0;
    int score3 = 0;
    int score4 = 0;
    
    //
    int turnCount = 0;
    int numPlayers = 0;
    
    int random1 = 0;
    int random2 = 0;
    int random3 = 0;
    int random4 = 0;
    int random5 = 0;
    
    int [] diceArray = new int [5];
    
    //Checking full house
    boolean hasPair = false;
    boolean hasThree = false;
    //Preset Scores
    final int FULL_HOUSE = 25;
    final int SM_STRAIGHT = 30;
    final int LG_STRAIGHT = 40;
    final int YAHTZEE = 50;
    final int BONUS = 100;
    boolean YahtzeeBonus1 = false;
    boolean YahtzeeBonus2 = false;
    boolean YahtzeeBonus3 = false;
    boolean YahtzeeBonus4 = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        category = new javax.swing.ButtonGroup();
        GamePage = new javax.swing.JPanel();
        rerollButton = new javax.swing.JButton();
        roll5 = new javax.swing.JLabel();
        roll3 = new javax.swing.JLabel();
        roll2 = new javax.swing.JLabel();
        roll1 = new javax.swing.JLabel();
        roll4 = new javax.swing.JLabel();
        rollButton = new javax.swing.JButton();
        upperSection = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lowerSection = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        endTurnButton = new javax.swing.JButton();
        largeStraight = new javax.swing.JRadioButton();
        aces = new javax.swing.JRadioButton();
        twos = new javax.swing.JRadioButton();
        threes = new javax.swing.JRadioButton();
        fours = new javax.swing.JRadioButton();
        fives = new javax.swing.JRadioButton();
        sixes = new javax.swing.JRadioButton();
        threeKind = new javax.swing.JRadioButton();
        fourKind = new javax.swing.JRadioButton();
        Yahtzee = new javax.swing.JRadioButton();
        chance = new javax.swing.JRadioButton();
        fullHouse = new javax.swing.JRadioButton();
        smallStraight = new javax.swing.JRadioButton();
        title = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        Start = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playCount = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        player3 = new javax.swing.JTextField();
        player4 = new javax.swing.JTextField();
        startGame = new javax.swing.JButton();
        Rules = new javax.swing.JButton();
        scorePage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreTable = new javax.swing.JTable();
        playButton = new javax.swing.JButton();
        dicePic = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GamePage.setBackground(new java.awt.Color(102, 102, 255));
        GamePage.setForeground(new java.awt.Color(255, 153, 0));
        GamePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rerollButton.setBackground(new java.awt.Color(102, 102, 255));
        rerollButton.setText("Re Roll");
        rerollButton.setEnabled(false);
        rerollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerollButtonActionPerformed(evt);
            }
        });
        GamePage.add(rerollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        roll5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll5.setForeground(new java.awt.Color(255, 255, 255));
        roll5.setText("?");
        GamePage.add(roll5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        roll3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll3.setForeground(new java.awt.Color(255, 255, 255));
        roll3.setText("?");
        GamePage.add(roll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        roll2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll2.setForeground(new java.awt.Color(255, 255, 255));
        roll2.setText("?");
        GamePage.add(roll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        roll1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll1.setForeground(new java.awt.Color(255, 255, 255));
        roll1.setText("?");
        GamePage.add(roll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        roll4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll4.setForeground(new java.awt.Color(255, 255, 255));
        roll4.setText("?");
        GamePage.add(roll4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        rollButton.setBackground(new java.awt.Color(102, 102, 255));
        rollButton.setText("Roll");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });
        GamePage.add(rollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aces", " Count and add only ones"},
                {"Twos", " Count and add only twos "},
                {"Threes", " Count and add only threes"},
                {"Fours", " Count and add only fours"},
                {"Fives", " Count and add only fives"},
                {"Sixes", " Count and add only sixes"},
                {"Bonus (Total score is 63 or over)", "                     Score 35"}
            },
            new String [] {
                "Upper Section", "How to Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(32);
        upperSection.setViewportView(jTable2);

        GamePage.add(upperSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 390, 260));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3 of a kind", " Add total of all dice"},
                {"4 of a kind", " Add total of all dice"},
                {"Full house", " Score 25"},
                {"Small straight (sequence of 4)", " Score 30"},
                {"Large straight (sequence of 5)", " Score 40"},
                {"Yahtzee (5 of a kind)", " Score 50"},
                {"Chance", " Add total of all 5 dice"},
                {"Yahtzee Bonus", " Score 100 for every Yahtzee after"}
            },
            new String [] {
                "Lower Section", "How to Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(32);
        lowerSection.setViewportView(jTable1);

        GamePage.add(lowerSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 360, 290));

        endTurnButton.setBackground(new java.awt.Color(102, 102, 255));
        endTurnButton.setText("End Turn");
        endTurnButton.setEnabled(false);
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });
        GamePage.add(endTurnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        largeStraight.setBackground(new java.awt.Color(102, 102, 255));
        category.add(largeStraight);
        largeStraight.setForeground(new java.awt.Color(255, 153, 0));
        largeStraight.setText("Large straight (5)");
        GamePage.add(largeStraight, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        aces.setBackground(new java.awt.Color(102, 102, 255));
        category.add(aces);
        aces.setForeground(new java.awt.Color(255, 153, 0));
        aces.setText("Aces");
        aces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acesActionPerformed(evt);
            }
        });
        GamePage.add(aces, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        twos.setBackground(new java.awt.Color(102, 102, 255));
        category.add(twos);
        twos.setForeground(new java.awt.Color(255, 153, 0));
        twos.setText("Twos");
        twos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twosActionPerformed(evt);
            }
        });
        GamePage.add(twos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        threes.setBackground(new java.awt.Color(102, 102, 255));
        category.add(threes);
        threes.setForeground(new java.awt.Color(255, 153, 0));
        threes.setText("Threes");
        GamePage.add(threes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        fours.setBackground(new java.awt.Color(102, 102, 255));
        category.add(fours);
        fours.setForeground(new java.awt.Color(255, 153, 0));
        fours.setText("Fours");
        GamePage.add(fours, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        fives.setBackground(new java.awt.Color(102, 102, 255));
        category.add(fives);
        fives.setForeground(new java.awt.Color(255, 153, 0));
        fives.setText("Fives");
        GamePage.add(fives, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        sixes.setBackground(new java.awt.Color(102, 102, 255));
        category.add(sixes);
        sixes.setForeground(new java.awt.Color(255, 153, 0));
        sixes.setText("Sixes");
        GamePage.add(sixes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        threeKind.setBackground(new java.awt.Color(102, 102, 255));
        category.add(threeKind);
        threeKind.setForeground(new java.awt.Color(255, 153, 0));
        threeKind.setText("3 of a kind");
        GamePage.add(threeKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        fourKind.setBackground(new java.awt.Color(102, 102, 255));
        category.add(fourKind);
        fourKind.setForeground(new java.awt.Color(255, 153, 0));
        fourKind.setText("4 of a kind");
        GamePage.add(fourKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        Yahtzee.setBackground(new java.awt.Color(102, 102, 255));
        category.add(Yahtzee);
        Yahtzee.setForeground(new java.awt.Color(255, 153, 0));
        Yahtzee.setText("Yahtzee (5 of a kind)");
        GamePage.add(Yahtzee, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        chance.setBackground(new java.awt.Color(102, 102, 255));
        category.add(chance);
        chance.setForeground(new java.awt.Color(255, 153, 0));
        chance.setText("Chance");
        GamePage.add(chance, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        fullHouse.setBackground(new java.awt.Color(102, 102, 255));
        category.add(fullHouse);
        fullHouse.setForeground(new java.awt.Color(255, 153, 0));
        fullHouse.setText("Full house");
        GamePage.add(fullHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        smallStraight.setBackground(new java.awt.Color(102, 102, 255));
        category.add(smallStraight);
        smallStraight.setForeground(new java.awt.Color(255, 153, 0));
        smallStraight.setText("Small straight (4)");
        smallStraight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallStraightActionPerformed(evt);
            }
        });
        GamePage.add(smallStraight, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Rosewood Std Regular", 0, 110)); // NOI18N
        title.setForeground(new java.awt.Color(255, 153, 0));
        title.setText("yahtzee");
        GamePage.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 440, -1));

        turnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        turnLabel.setForeground(new java.awt.Color(255, 255, 255));
        turnLabel.setText("It's ____'s Turn");
        GamePage.add(turnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(GamePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        Start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setBackground(new java.awt.Color(255, 255, 255));
        title1.setFont(new java.awt.Font("Rosewood Std Regular", 0, 110)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 153, 0));
        title1.setText("yahtzee");
        Start.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 440, -1));

        jLabel1.setFont(new java.awt.Font("AdLib Win95BT", 0, 14)); // NOI18N
        jLabel1.setText("What are their names?");
        Start.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        playCount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Player", "2 Players", "3 Players", "4 Players" }));
        playCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playCountActionPerformed(evt);
            }
        });
        Start.add(playCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("AdLib Win95BT", 0, 14)); // NOI18N
        jLabel2.setText("How many people are playing?");
        Start.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));
        Start.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, -1));
        Start.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 260, 90, -1));

        player3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3ActionPerformed(evt);
            }
        });
        Start.add(player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, -1));
        Start.add(player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 310, 90, -1));

        startGame.setText("Start Game");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });
        Start.add(startGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 90, -1));

        Rules.setText("Rules");
        Rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesActionPerformed(evt);
            }
        });
        Start.add(Rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 90, 30));

        getContentPane().add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        scorePage.setBackground(new java.awt.Color(102, 102, 255));
        scorePage.setForeground(new java.awt.Color(255, 153, 0));
        scorePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(scoreTable);

        scorePage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, 100));

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        scorePage.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        dicePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yahtzee/multiple-white-dice-black-spots-7666156.jpg"))); // NOI18N
        scorePage.add(dicePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        title2.setBackground(new java.awt.Color(255, 255, 255));
        title2.setFont(new java.awt.Font("Rosewood Std Regular", 0, 110)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 153, 0));
        title2.setText("yahtzee");
        scorePage.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 440, -1));

        getContentPane().add(scorePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twosActionPerformed

    private void smallStraightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallStraightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallStraightActionPerformed

    private void player3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3ActionPerformed

    private void playCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playCountActionPerformed
        //Decide how many players and then enables boxes for names
        if (playCount.getSelectedIndex() == 0) {
            player1.setEnabled(true);
            player2.setEnabled(false);
            player3.setEnabled(false);
            player4.setEnabled(false);
            numPlayers = 1;
        }
        else if (playCount.getSelectedIndex() == 1) {
            player1.setEnabled(true);
            player2.setEnabled(true);
            player3.setEnabled(false);
            player4.setEnabled(false);
            numPlayers = 2;
        }
        else if (playCount.getSelectedIndex() == 2) {
            player1.setEnabled(true);
            player2.setEnabled(true);
            player3.setEnabled(true);
            player4.setEnabled(false);
            numPlayers = 3;
        }
        else {
            player1.setEnabled(true);
            player2.setEnabled(true);
            player3.setEnabled(true);
            player4.setEnabled(true);
            numPlayers = 4;
        }
    }//GEN-LAST:event_playCountActionPerformed

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        //Get text and start game
        if (playCount.getSelectedIndex() == 0) {
            name1 = player1.getText();
        }
        else if (playCount.getSelectedIndex() == 1) {
            name1 = player1.getText();
            name2 = player2.getText();
        }
        else if (playCount.getSelectedIndex() == 2) {
            name1 = player1.getText();
            name2 = player2.getText();
            name3 = player3.getText();
        }
        else {
            name1 = player1.getText();
            name2 = player2.getText();
            name3 = player3.getText();
            name4 = player4.getText();
        }
        scoreTable.setValueAt(name1, 0, 0);
        scoreTable.setValueAt(name2, 1, 0);
        scoreTable.setValueAt(name3, 2, 0);
        scoreTable.setValueAt(name4, 3, 0);
        scoreTable.setValueAt(score1, 0, 1);
        scoreTable.setValueAt(score2, 1, 1);
        scoreTable.setValueAt(score3, 2, 1);
        scoreTable.setValueAt(score4, 3, 1);
        scorePage.setVisible(true);
        Start.setVisible(false);
    }//GEN-LAST:event_startGameActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        scorePage.setVisible(false);
        GamePage.setVisible(true);
        if (turnCount == 0) {
            turnLabel.setText("It's " + name1 + "'s turn");
        }
        else if (turnCount == 1) {
            turnLabel.setText("It's " + name2 + "'s turn");
        }
        else if (turnCount == 2) {
            turnLabel.setText("It's " + name3 + "'s turn");
        }
        else {
            turnLabel.setText("It's " + name4 + "'s turn");
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        //Random numbers variables
        random1 = (int)Math.round(Math.random()*5+1);
        random2 = (int)Math.round(Math.random()*5+1);
        random3 = (int)Math.round(Math.random()*5+1);
        random4 = (int)Math.round(Math.random()*5+1);       
        random5 = (int)Math.round(Math.random()*5+1);
        
        //Output numbers
        roll1.setText(String.valueOf(random1));
        roll2.setText(String.valueOf(random2));
        roll3.setText(String.valueOf(random3));
        roll4.setText(String.valueOf(random4));
        roll5.setText(String.valueOf(random5));
        
        //Set to array
        diceArray[0] = random1;
        diceArray[1] = random2;
        diceArray[2] = random3;
        diceArray[3] = random4;
        diceArray[4] = random5;
        Arrays.sort(diceArray);
        
        //Check for Three of a kind
        for (int i = 0; i < 3; i++) {
                if (diceArray[i] == diceArray[i+1] && diceArray[i] == diceArray[i+2]) {
                    threeKind.setEnabled(true);
                    i = 4;
                }
                else {
                    threeKind.setEnabled(false);
                }
            }
        //Check for Four of a Kind
        for (int i = 0; i < 2; i++) {
                if (diceArray[i] == diceArray[i+1] && diceArray[i] == diceArray[i+2] && diceArray[i] == diceArray[i+3]) {
                    fourKind.setEnabled(true);
                    i = 3;
                }
                else {
                    fourKind.setEnabled(false);
                }
            }
        //Check for Full House
        for (int i = 0; i < 4; i++) {
                if (diceArray[i] == diceArray[i+1]) {
                    hasPair = true;
                    diceArray[i] = 7;
                    diceArray[i+1] = 7; 
                    i = 4;
                }
                else {
                    hasPair = false;
                }
            }
        for (int i = 0; i < 3; i++) {
                if (diceArray[i] == diceArray[i+1] && diceArray[i] == diceArray[i+2]) {
                    hasThree = true; 
                    i = 4;
                }
                else {
                    hasThree = false;
                }
            }
        if (hasPair == true && hasThree == true) {
            fullHouse.setEnabled(true);
        }
        else {
            fullHouse.setEnabled(false);
        }
        //Check for small straight FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX
        if (diceArray[3] - diceArray[0] == 3 || diceArray[4] - diceArray[1] == 3) {
            largeStraight.setEnabled(true);
        }
        else {
            largeStraight.setEnabled(false);
        }
        
        //Check for large straight
        for (int i = 0; i < 4; i++) {
            if (diceArray[i] + 1 == diceArray[i+1]) {
                largeStraight.setEnabled(true);
            }
            else {
                largeStraight.setEnabled(false);
                i = 4;
            }
        }
        
        //Check for Yahtzee
        for (int i = 0; i < 1; i++) {
                if (diceArray[i] == diceArray[i+1] && diceArray[i] == diceArray[i+2] && diceArray[i] == diceArray[i+3] && diceArray[i] == diceArray[i+4]) {
                    Yahtzee.setEnabled(true);
                    i = 2;
                }
                else {
                    Yahtzee.setEnabled(false);
                }
            }
        //Setup for re roll
        rollButton.setEnabled(false);
        rerollButton.setEnabled(true);
        endTurnButton.setEnabled(true);
    }//GEN-LAST:event_rollButtonActionPerformed

    private void rerollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerollButtonActionPerformed
        
    }//GEN-LAST:event_rerollButtonActionPerformed

    private void RulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesActionPerformed
        try {
                    Desktop.getDesktop().browse(new URI("https://docs.google.com/document/d/1p1zD98FQYYBEBNnEBhoGrpwI9Fd3C7gK16iQRNCXsrw/edit?usp=sharing"));
                } catch (IOException | URISyntaxException e1) {
                    e1.printStackTrace();
                }
    }//GEN-LAST:event_RulesActionPerformed

    private void acesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acesActionPerformed
        
    }//GEN-LAST:event_acesActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        UpperSection();
        LowerSection();
        if (turnCount == 0) {
            scoreTable.setValueAt(score1, 0, 1);
            System.out.println(score1);
        }
        else if (turnCount == 1) {
            scoreTable.setValueAt(score2, 1, 1);
            System.out.println(score2);
        }
        else if (turnCount == 2) {
            scoreTable.setValueAt(score3, 2, 1);
            System.out.println(score3);
        }
        else {
            scoreTable.setValueAt(score4, 3, 1);
            System.out.println(score4);
        }
        turnOrder();
        scorePage.setVisible(true);
        GamePage.setVisible(false);
        
    }//GEN-LAST:event_endTurnButtonActionPerformed

    public void UpperSection() {
        Aces();
        Twos();
        Threes();
        Fours();
        Fives();
        Sixes();
    }
    
    public void LowerSection() {
        ThreeKind();
        FourKind();
        FullHouse();
        SmStraight();
        LgStraight();
        Yahtzee();
        Chance();
    }
    
    public void Aces() {
        //Add all ones
        if (aces.isSelected()) {
            System.out.println("E");
            if (random1 == 1) {
                if (turnCount == 0) {
                    score1 = score1 + 1;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 1;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 1;
                }
                else {
                    score4 = score4 + 1; 
                }
            }
            if (random2 == 1) {
                if (turnCount == 0) {
                score1 = score1 + 1;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 1;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 1;
                }
                else {
                    score4 = score4 + 1; 
                }
            }
            if (random3 == 1) {
                if (turnCount == 0) {
                    score1 = score1 + 1;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 1;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 1;
                }
                else {
                    score4 = score4 + 1; 
                }
            }
            if (random4 == 1) {
                if (turnCount == 0) {
                    score1 = score1 + 1;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 1;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 1;
                }
                else {
                    score4 = score4 + 1; 
                }
            }
            if (random5 == 1) {
                if (turnCount == 0) {
                    score1 = score1 + 1;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 1;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 1;
                }
                else {
                    score4 = score4 + 1; 
                }
            }
        }
    }
    
    public void Twos() {
        //Add all twos
        if(twos.isSelected()) {
            if (random1 == 2) {
                if (turnCount == 0) {
                    score1 = score1 + 2;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 2;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 2;
                }
                else {
                    score4 = score4 + 2; 
                }
            }
            if (random2 == 2) {
                if (turnCount == 0) {
                score1 = score1 + 2;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 2;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 2;
                }
                else {
                    score4 = score4 + 2; 
                }
            }
            if (random3 == 2) {
                if (turnCount == 0) {
                    score1 = score1 + 2;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 2;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 2;
                }
                else {
                    score4 = score4 + 2; 
                }
            }
            if (random4 == 2) {
                if (turnCount == 0) {
                    score1 = score1 + 2;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 2;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 2;
                }
                else {
                    score4 = score4 + 2; 
                }
            }
            if (random5 == 2) {
                if (turnCount == 0) {
                    score1 = score1 + 2;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 2;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 2;
                }
                else {
                    score4 = score4 + 2; 
                }
            }
        }
    }
    
    public void Threes() {
        //Add all threes
        if(threes.isSelected()) {
            if (random1 == 3) {
                if (turnCount == 0) {
                    score1 = score1 + 3;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 3;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 3;
                }
                else {
                    score4 = score4 + 3; 
                }
            }
            if (random2 == 3) {
                if (turnCount == 0) {
                    score1 = score1 + 3;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 3;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 3;
                }
                else {
                    score4 = score4 + 3; 
                }
            }
            if (random3 == 3) {
                if (turnCount == 0) {
                    score1 = score1 + 3;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 3;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 3;
                }
                else {
                    score4 = score4 + 3; 
                }
            }
            if (random4 == 3) {
                if (turnCount == 0) {
                    score1 = score1 + 3;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 3;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 3;
                }
                else {
                    score4 = score4 + 3; 
                }
            }
            if (random5 == 3) {
                if (turnCount == 0) {
                    score1 = score1 + 3;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 3;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 3;
                }
                else {
                    score4 = score4 + 3; 
                }
            }
        }
    }
    
    public void Fours() {
        //Add all fours
        if(fours.isSelected()) {
                System.out.println("E");
            if (random1 == 4) {
                if (turnCount == 0) {
                    score1 = score1 + 4;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 4;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 4;
                }
                else {
                    score4 = score4 + 4; 
                }
            }
            if (random2 == 4) {
                if (turnCount == 0) {
                    score1 = score1 + 4;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 4;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 4;
                }
                else {
                    score4 = score4 + 4; 
                }
            }
            if (random3 == 4) {
                if (turnCount == 0) {
                    score1 = score1 + 4;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 4;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 4;
                }
                else {
                    score4 = score4 + 4; 
                }
            }
            if (random4 == 4) {
                if (turnCount == 0) {
                    score1 = score1 + 4;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 4;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 4;
                }
                else {
                    score4 = score4 + 4; 
                }
            }
            if (random5 == 4) {
                if (turnCount == 0) {
                    score1 = score1 + 4;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 4;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 4;
                }
                else {
                    score4 = score4 + 4; 
                }
            }
        }
    }
    
    public void Fives() {
        //Add all fives
        if(fives.isSelected()) {
            if (random1 == 5) {
                if (turnCount == 0) {
                    score1 = score1 + 5;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 5;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 5;
                }
                else {
                    score4 = score4 + 5; 
                }
            }
            if (random2 == 5) {
                if (turnCount == 0) {
                    score1 = score1 + 5;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 5;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 5;
                }
                else {
                    score4 = score4 + 5; 
                }
            }
            if (random3 == 5) {
                if (turnCount == 0) {
                    score1 = score1 + 5;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 5;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 5;
                }
                else {
                    score4 = score4 + 5; 
                }
            }
            if (random4 == 5) {
                if (turnCount == 0) {
                    score1 = score1 + 5;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 5;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 5;
                }
                else {
                    score4 = score4 + 5; 
                }
            }
            if (random5 == 5) {
                if (turnCount == 0) {
                    score1 = score1 + 5;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 5;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 5;
                }
                else {
                    score4 = score4 + 5; 
                }
            }
        }
    }
    
    public void Sixes() {
        //Add all sixes
        if(sixes.isSelected()) {
            if (random1 == 6) {
                if (turnCount == 0) {
                    score1 = score1 + 6;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 6;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 6;
                }
                else {
                    score4 = score4 + 6; 
                }
            }
            if (random2 == 6) {
                if (turnCount == 0) {
                    score1 = score1 + 6;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 6;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 6;
                }
                else {
                    score4 = score4 + 6; 
                }
            }
            if (random3 == 6) {
                if (turnCount == 0) {
                    score1 = score1 + 6;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 6;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 6;
                }
                else {
                    score4 = score4 + 6; 
                }
            }
            if (random4 == 6) {
                if (turnCount == 0) {
                    score1 = score1 + 6;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 6;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 6;
                }
                else {
                    score4 = score4 + 6; 
                }
            }
            if (random5 == 6) {
                if (turnCount == 0) {
                    score1 = score1 + 6;
                }
                else if (turnCount == 1) {
                    score2 = score2 + 6;
                }
                else if (turnCount == 2) {
                    score3 = score3 + 6;
                }
                else {
                    score4 = score4 + 6; 
                }
            }
        }
    }
    
    public void ThreeKind() {
        
        if (threeKind.isSelected()) {
            if (turnCount == 0) {
                score1 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 1) {
                score2 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 2) {
                score3 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 3) {
                score4 = random1 + random2 + random3+ random4 + random5;
            }
        }
    }
    
    public void FourKind() {
        if (fourKind.isSelected()) {
            if (turnCount == 0) {
                score1 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 1) {
                score2 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 2) {
                score3 = random1 + random2 + random3+ random4 + random5;
            }
            else if (turnCount == 3) {
                score4 = random1 + random2 + random3+ random4 + random5;
            }
        }
    }
    
    public void FullHouse() {
        if (fullHouse.isSelected()) {
            if (turnCount == 0) {
                score1 = score1 + 25;
            }
            else if (turnCount == 1) {
                score2 = score2 + 25;
            }
            else if (turnCount == 2) {
                score3 = score3 + 25;
            }
            else if (turnCount == 3) {
                score4 = score4 + 25;
            }
        }
    }
    
    public void SmStraight() {
        
    }
    
    public void LgStraight() {
        
    }
    
    public void Yahtzee() {
        if (Yahtzee.isSelected()) {
            if (YahtzeeBonus1 == false && turnCount == 0) {
                    score1 = score1 + YAHTZEE;
            }
            else if (YahtzeeBonus1 == true && turnCount == 0) {
                    score1 = score1 + BONUS;
            }
            else if (YahtzeeBonus2 == false && turnCount == 1) {
                    score2 = score2 + YAHTZEE;
            }
            else if (YahtzeeBonus2 == true && turnCount == 1) {
                    score2 = score2 + BONUS;
            }
            else if (YahtzeeBonus3 == false && turnCount == 2) {
                    score3 = score3 + YAHTZEE;
            }
            else if (YahtzeeBonus3 == true && turnCount == 2) {
                    score3 = score3 + BONUS;
            }
            else if (YahtzeeBonus4 == false && turnCount == 3) {
                    score4 = score4 + YAHTZEE;
            }
            else if (YahtzeeBonus4 == true && turnCount == 3) {
                    score4 = score4 + BONUS;
            }
        }
    }
    
    public void Chance() {
        
    }
    
    public void turnOrder() {
        if (numPlayers == 1) {
            turnCount = 0;
        }
        else if (numPlayers == 2) {
            if (turnCount != 1) {
                turnCount = turnCount + 1;
            }
            else {
                turnCount = 0;
            }
        }
        else if (numPlayers == 3) {
            if (turnCount != 2) {
                turnCount = turnCount + 1;
            }
            else {
                turnCount = 0;
            }
        }
        else if (numPlayers == 4) {
            if (turnCount != 3) {
                turnCount = turnCount + 1;
            }
            else {
                turnCount = 0;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yahtzee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yahtzee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yahtzee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yahtzee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yahtzee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GamePage;
    private javax.swing.JButton Rules;
    private javax.swing.JPanel Start;
    private javax.swing.JRadioButton Yahtzee;
    private javax.swing.JRadioButton aces;
    private javax.swing.ButtonGroup category;
    private javax.swing.JRadioButton chance;
    private javax.swing.JLabel dicePic;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JRadioButton fives;
    private javax.swing.JRadioButton fourKind;
    private javax.swing.JRadioButton fours;
    private javax.swing.JRadioButton fullHouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton largeStraight;
    private javax.swing.JScrollPane lowerSection;
    private javax.swing.JButton playButton;
    private javax.swing.JComboBox playCount;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JTextField player3;
    private javax.swing.JTextField player4;
    private javax.swing.JButton rerollButton;
    private javax.swing.JLabel roll1;
    private javax.swing.JLabel roll2;
    private javax.swing.JLabel roll3;
    private javax.swing.JLabel roll4;
    private javax.swing.JLabel roll5;
    private javax.swing.JButton rollButton;
    private javax.swing.JPanel scorePage;
    private javax.swing.JTable scoreTable;
    private javax.swing.JRadioButton sixes;
    private javax.swing.JRadioButton smallStraight;
    private javax.swing.JButton startGame;
    private javax.swing.JRadioButton threeKind;
    private javax.swing.JRadioButton threes;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JRadioButton twos;
    private javax.swing.JScrollPane upperSection;
    // End of variables declaration//GEN-END:variables
}
